	.ORIG	x3000
	LD	R1, NUMA
	LD	R2, NUMB
	LD	R3, NUMC
	LD	R4, POSSIG

ROUND	JSR	STATS
STATEND	ADD	R4, R4, #0
	BRp	PLYR1
	BRn	PLYR2

PLYR1	LEA	R0, PROMPTA
	TRAP	x22
	BRnzp	NIM

PLYR2	LEA	R0, PROMPTB
	TRAP	x22
	BRnzp	NIM

NIM	TRAP	x20
	TRAP	x21
	NOT	R5, R0
	ADD	R5, R5, #1
	LD	R6, ASCIIA
	ADD	R7, R6, R5
	BRz	NIMA
	LD	R6, ASCIIB
	ADD	R7, R6, R5
	BRz	NIMB
	LD	R6, ASCIIC
	ADD	R7, R6, R5
	BRz	NIMC
	BRnzp	FAIL

NIMA	TRAP	x20
	TRAP	x21
	LD	R5, ASCFIX
	ADD	R0, R0, R5
	BRnz	FAIL
	AND	R5, R5, #0
	ADD	R5, R5, #-10
	ADD	R5, R5, R0
	BRzp	FAIL
	
	NOT	R5, R0
	ADD	R5, R5, #1
	ADD	R5, R5, R1
	BRn	FAIL
	ADD	R1, R5, #0
	ADD	R4, R4, #0
	BRp	ARND1
	BRn	ARND2
ARND1	LD	R4, NEGSIG
	BRnzp	ROUND

ARND2	LD	R4, POSSIG
	BRnzp	ROUND
	

	
NIMB	TRAP	x20
	TRAP	x21
	LD	R5, ASCFIX
	ADD	R0, R0, R5
	BRnz	FAIL
	AND	R5, R5, #0
	ADD	R5, R5, #-10
	ADD	R5, R5, R0
	BRzp	FAIL
	
	NOT	R5, R0
	ADD	R5, R5, #1
	ADD	R5, R5, R2
	BRn	FAIL
	ADD	R2, R5, #0
	ADD	R4, R4, #0
	BRp	BRND1
	BRn	BRND2
BRND1	LD	R4, NEGSIG
	BRnzp	ROUND

BRND2	LD	R4, POSSIG
	BRnzp	ROUND


NIMC	TRAP	x20
	TRAP	x21
	LD	R5, ASCFIX
	ADD	R0, R0, R5
	BRnz	FAIL
	AND	R5, R5, #0
	ADD	R5, R5, #-10
	ADD	R5, R5, R0
	BRzp	FAIL
	
	NOT	R5, R0
	ADD	R5, R5, #1
	ADD	R5, R5, R3
	BRn	FAIL
	ADD	R3, R5, #0
	ADD	R4, R4, #0
	BRp	CRND1
	BRn	CRND2
CRND1	LD	R4, NEGSIG
	BRnzp	ROUND

CRND2	LD	R4, POSSIG
	BRnzp	ROUND
	

FAIL	LEA	R0, ERROR
	TRAP	x22
	BRnzp	ROUND

	

STATS	LEA	R0, ROWA
	TRAP	x22
	LD	R5, NIMO
	ADD	R6, R1, #0

SYMB1	BRnz	NEXT2
	STI	R5, DDR
	ADD	R6, R6, #-1
	BRnzp	SYMB1

NEXT2	LEA	R0, ROWB
	TRAP	x22
	LD	R5, NIMO
	ADD	R6, R2, #0

SYMB2	BRnz	NEXT3
	STI	R5, DDR
	ADD	R6, R6, #-1
	BRnzp	SYMB2
		
NEXT3	LEA	R0, ROWC
	TRAP	x22
	LD	R5, NIMO
	ADD	R6, R3, #0

SYMB3	BRnz	ALL
	STI	R5, DDR
	ADD	R6, R6, #-1
	BRnzp	SYMB3
ALL	ADD	R5, R1, R2
	ADD	R5, R5, R3
	BRnz	OVER
	BRnzp	STATEND

OVER	ADD	R4, R4, #0
	BRp	AWIN
	BRn	BWIN
AWIN	LEA	R0, WINA
	TRAP	x22
	HALT
BWIN	LEA	R0, WINB
	TRAP	x22
	HALT

NUMA	.FILL	x0003
NUMB	.FILL	x0005
NUMC	.FILL	x0008
POSSIG	.FILL	x0001
NEGSIG	.FILL	xFFFF
NIMO	.FILL	x006F

DSR	.FILL	xFE04
DDR	.FILL	xFE06
KBSR	.FILL	xFE00
KBDR	.FILL	xFE02

ASCIIA	.FILL	x0041
ASCIIB	.FILL	x0042
ASCIIC	.FILL	x0043
ASCFIX	.FILL	xFFD0

PROMPTA	.STRINGZ	"\nPlayer 1, choose a row and number of rocks: "
PROMPTB	.STRINGZ	"\nPlayer 2, choose a row and number of rocks: "
ERROR	.STRINGZ	"\nInvalid move. Try again."
ROWA	.STRINGZ	"\nROW A: "
ROWB	.STRINGZ	"\nROW B: "
ROWC	.STRINGZ	"\nROW C: "
ENDLINE	.STRINGZ	"\n"
WINA	.STRINGZ	"\nPlayer 1 Wins."
WINB	.STRINGZ	"\nPlayer 2 Wins."
	.END